- id: doi:10.3389/fpls.2023.1177406
  image: https://www.turing.ac.uk/sites/default/files/2019-01/crop_ontology_logo.png
  date: "2023-05-15"
  buttons:
    - type: journal
      link: https://doi.org/10.3389/fpls.2023.1177406
