- id: doi:10.3389/fpls.2023.1177406 
  title: Sainfoin (Onobrychis spp.) crop ontology: supporting germplasm characterization and international research collaborations
  authors: 
    - Ebrar Karabulut
    - Kübra Erkoç
    - Murat Acı
    - Mahmut Aydın
    - Spencer Barriball
    - Jackson Braley
    - Eric Cassetta
    - Evan B. Craine
    - Luis Diaz-Garcia
    - Jenna Hershberger
    - Bo Meyering
    - Allison J. Miller
    - Matthew J. Rubin
    - Omar Tesdell
    - Brandon Schlautman
    - Muhammet Şakiroğlu
  publisher: Frontiers in Plant Science 
  date: 2023-05-15
  doi: 10.3389/fpls.2023.1177406 
  link: http://dx.doi.org/10.3389/fpls.2023.1177406 

